# for planner logic
map_size_ub : [10.0, 10.0] # górne wymairy mapy
map_size_lb : [-10.0, -10.0] # dolne wymiary mapy
step_size : 0.1 # długość kroku algorytmu
max_ierations : 1000  # liczba iteracji algorytmu
generate_chance : 0.2 # szansa że losowy node to cel
search_radius : 0.1 # odległość w której szuka sąsiadów 
goal_radius : 0.15  # odległość w której uznaje że dotarł do celu

# for visualization
sizes : [0.2, 0.2, 0.2]
height : 0.1